### ISSUE TITLE
No option to configure host

### ISSUE THREAD

**Issue by willwillems** [alejandromav/tinybird-action-push#1]
When using "https://api.us-east.tinybird.co" I get a `** Forbidden: invalid authentication token` error when just using the Tinybird token. Currently it's not possible to specify the host using this action?

We're currently using: https://github.com/willwillems/tinybird-action-push, I'd make a PR but this makes the host required which you guys probably don't want.

Two other notes:
- The action does not fail on this error, it's status shows as succeeded
- The checkout action in the example uses v2 which uses the deprecated node12 runtime, v3 uses node16

Thanks for creating this, besides this small issue it works well

**Comment by alejandromav** [comment]
Hey! 👋

Thanks a lot for the feedback, let me have a look and I'll get back to you in a couple of days.

**Comment by alejandromav** [comment]
BTW, you can just open the PR and we'll continue there.

Thanks!

**Comment by alejandromav** [comment]
Hey @willwillems ! 

Should work now, just make sure you're using version `1.2.0` or greater. For example:

```yaml
name: Push changes to Tinybird

on:
  push:
    branches:
    - master
    - main
    - stable
    - release/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push changes to Tinybird
      uses: alejandromav/tinybird-action-push@1.2.0
      with:
        token: ${{ secrets.TINYBIRD_TOKEN }}
        host: https://api.us-east.tinybird.co

```

Details here #3
